# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 https://sanderbeckers.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             /website

title:               Sander

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Welcome to the personal webpage of Sander Beckers. 

# The tags listed as entries in the sidebar
sidebar_tags:        [articles, talks, cv]

# Fallback image and color if not overwritten for tag or post
image:               /website/sander/background44.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Sander Beckers'

  # This photo will be used in the about section
  photo:             /website/sander/profile_picture.jpg
  #photo2x:          

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:            |
    Welcome to my personal webpage, and thanks for taking the time to pay it a visit. I       am currently a visiting postdoctoral research fellow at the Cornell University            Department of Computer Science. 
	
	I have a background in philosophy, mathematics,     and Artificial Intelligence, and for the past five years I have been working across       the boundary between philosophy of science and Artificial Intelligence. PAR Before        coming to Cornell, I wrote a PhD on the topic of Actual Causation at the University       of Leuven, Department of Computer Science. My current research extends the work on        causation into formal ethics. Concretely, I am now working on formalising definitions     of responsibility, intention, and blameworthiness, taking formal definitions of           causation as my starting point. PAR However my interests are not limited to these         problems but span a much wider range of topics, such as the ethics of AI, the             (ir)rationality of belief in the supernatural,the meaning of randomness, philosophy       of mathematics, bounded rationality, Wittgenstein's philosophy, cultural relativism,      and many more. PAR If you are interested in my work, then do not hesitate to send me      an e-mail at
	
    

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    facebook:        bedenkzelfiets 
    #twitter:         _username_
    #google:          _number_
    #vk:              _username_
    #youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # github:          _username_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    linkedin:        sander-beckers-00136aab
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Analytics
#google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
